# Numpy

In [2]:
import numpy as np

In [4]:
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [6]:
test_array[3]

8.0

In [7]:
test_array[2:]

array([5., 8.])

In [8]:
test_array.dtype, test_array.shape

(dtype('float64'), (4,))

# 2. Array Shape

In [9]:
#Vector (1차원)
test_array = np.array([1,4,5,8], float)
test_array.shape

(4,)

In [10]:
#Matrix (2차원 행렬)
matrix = [[1,2,5,8],[2,3,4,9],[4,5,6,7]]
np.array(matrix,int).shape

(3, 4)

In [11]:
np.array(matrix,int)

array([[1, 2, 5, 8],
       [2, 3, 4, 9],
       [4, 5, 6, 7]])

In [12]:
matrix

[[1, 2, 5, 8], [2, 3, 4, 9], [4, 5, 6, 7]]

In [14]:
tensor = [[[1,2,5,8], [2,3,4,9], [4,5,6,7]],
          [[1,2,5,8], [2,3,4,9], [4,5,6,7]],
          [[1,2,5,8], [2,3,4,9], [4,5,6,7]],
          [[1,2,5,8], [2,3,4,9], [4,5,6,7]]]
np.array(tensor, int).shape


(4, 3, 4)

In [16]:
np.array(tensor, int).ndim

3

In [17]:
np.array(tensor, int).size

48

## Reshape

In [19]:
test_matrix = [[1,2,3,4], [5,6,7,8]]
np.array(test_matrix).shape

(2, 4)

In [21]:
np.array(test_matrix).reshape(8, )  

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
np.array(test_matrix).reshape(8, ).shape  

(8,)

In [23]:
np.array(test_matrix).reshape(2, 4).shape  

(2, 4)

In [24]:
np.array(test_matrix).reshape(-1, 2).shape 

(4, 2)

In [25]:
np.array(test_matrix).reshape(2, 2, 2).shape  

(2, 2, 2)

In [26]:
test_matrix = [[[1,2,3,4], [5,6,7,8]], [[2,3,4,5], [6,7,8,9]]]
np.array(test_matrix).flatten()


array([1, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.array(test_matrix).reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## Indexing

In [29]:
a = np.array([[1,2,3], [4,5,6]], int)
print(a)


[[1 2 3]
 [4 5 6]]


In [30]:
print(a[0,0])   

1


In [31]:
print(a[0][0])  

1


In [33]:
a[1,2]


6

In [35]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
a[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [37]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [38]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.empty((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)
np.zeros_like(test_matrix)


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [41]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [43]:
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random Sampling

In [44]:
np.random.seed(seed=1000)

In [45]:
np.random.uniform(0, 1, 10).reshape(2,5)

array([[0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454],
       [0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072]])

In [46]:
np.random.normal(0, 1, 10).reshape(2,5)

array([[ 0.66728131, -0.80611561, -1.19606983, -0.40596016, -0.18237734],
       [ 0.10319289, -0.13842199,  0.70569237,  1.27179528, -0.98674733]])

In [50]:
test_array = np.arange(1,11)
test_array.sum(dtype=np.float)  

55.0

In [52]:
test_array = np.arange(1,13).reshape(3,4)

In [53]:
test_array.sum(axis=1)

array([10, 26, 42])

In [54]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [55]:
test_array = np.arange(1,13).reshape(3,4)

In [56]:
test_array.mean() 

6.5

In [58]:
test_array.mean(axis=0)

array([5., 6., 7., 8.])

In [59]:
test_array.std()		# 표준 편차(Standard Deviation)
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [60]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [62]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [69]:
test_a = np.array([[1,2,3], [4,5,6]], float)
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [71]:
test_a - test_a
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [72]:
test_a = np.arange(1,7).reshape(2,3)

In [73]:
test_b = np.arange(7,13).reshape(3,2)

In [74]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [76]:
test_a = np.arange(1,7).reshape(2,3)

In [78]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [79]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [80]:
test_matrix = np.array([[1,2,3], [4,5,6]], float)
scalar = 3
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [83]:
test_matrix ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [84]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [85]:
a = np.arange(10)

In [86]:
np.any(a>5)

True

In [87]:
np.any(a<0)

False

In [88]:
np.all(a>5)

False

In [89]:
np.all(a<10)

True

In [90]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [91]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [92]:
test_a == test_b
(test_a > test_b).any()

True

## Logical operation

In [4]:
a = np.array([1, 3, 0], float)
b = np.logical_and(a>0, a<3)

In [5]:
c = np.logical_not(b)

In [7]:
np.logical_or(b,c)

array([ True,  True,  True])

In [8]:
np.where(a>0, 3, 2)

array([3, 3, 2])

In [9]:
a = np.arange(10, 20)
np.where(a>15)

(array([6, 7, 8, 9], dtype=int64),)

In [11]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)
np.isfinite(a)

array([ True, False, False])

In [12]:
#3항 연산자
x = 3
y = True if x > 0 else False
y

True

In [14]:
y = '조건이 만족했을 경우의 값' if x > 0 else '조건이 틀린 경우의 값'
y

'조건이 만족했을 경우의 값'

In [15]:
if x > 0 :
    y = '조건이 만족했을 경우의 값'
else:
    y = '조건이 틀린 경우의 값'

In [16]:
a = np.arange(10,20)
np.where(a>15)

(array([6, 7, 8, 9], dtype=int64),)

In [18]:
a = np.array([1,np.NaN,np.Inf],float)
a

array([ 1., nan, inf])

In [19]:
np.isnan(a)

array([False,  True, False])

In [20]:
np.isfinite(a)

array([ True, False, False])

In [21]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a)

5

In [22]:
np.argmin(a)

0

In [23]:
a = np.array([[1,2,4,7],[9,88,6,45],[8,78,23,3]])
np.argmax(a), np.argmin(a)

(5, 0)

In [24]:
a = np.array([[1,2,4,7],[9,88,6,45],[8,78,23,3]])
np.argmax(a, axis=1)

array([3, 1, 1], dtype=int64)

In [25]:
np.argmax(a, axis=0)

array([1, 1, 2, 1], dtype=int64)

In [26]:
np.argmin(a, axis=1)

array([0, 2, 3], dtype=int64)

In [27]:
np.argmin(a, axis=0)

array([0, 0, 0, 2], dtype=int64)

In [28]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [29]:
test_array[test_array > 3]  

array([4., 8., 9., 7.])

In [30]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [32]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b] 

array([2., 2., 4., 8., 6., 4.])

In [33]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [34]:
a = np.array([[1,4], [9,16]], float)
b = np.array([0,0,1,1,1], int)
c = np.array([0,1,1,1,0], int)
a[b,c]

array([ 1.,  4., 16., 16.,  9.])

In [48]:
# 예제 13-13

import csv
f = open('school_2019.csv','r', encoding='utf-8')
lines = csv.reader(f)

header = next(lines)

list_data = []
for line in lines :
    list_data.append(line[:])
    
length = len(list_data)
print(length)

data = np.zeros((length,3), dtype = 'int32')

for i in range(length) :
    for j in range(3) :
        data[i][j] = list_data[i][j+2]
        
print(data)

f.close()

6264
[[ 28 616  32]
 [ 31 632  35]
 [ 31 837  38]
 ...
 [ 36 985  42]
 [ 34 862  41]
 [ 26 603  31]]


In [ ]:
# 예제 13-13
import csv
import numpy as np

