In [1]:
import numpy as np

In [2]:
#1 길이가 10인 0-벡터를 만드세요.
zero_vector = np.zeros((10), dtype = np.int8)
print(zero_vector)

[0 0 0 0 0 0 0 0 0 0]


In [5]:
#2 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요
element5 = np.zeros((10), dtype = np.int8)
element5[4] = 1
print(element5)

[0 0 0 0 1 0 0 0 0 0]


In [7]:
#3 10 부터 49까지의 값을 가지는 벡터를 만드세요.
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#4 위(3번) 벡터의 순서를 바꾸세요.
reverse_vector = vector [::-1]
print(reverse_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
#5 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.
vector = np.arange(0,9).reshape(3,3)
print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
#6 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.
vector_1 = np.array([1,2,0,0,4,0], int)
vector_2 = vector_1[vector_1 > 0]
print(vector_2)

[1 2 4]


In [12]:
#7 3x3 단위 행렬(identity matrix)을 만드세요
vector = np.identity(3)
print(vector)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#8 난수 원소를 가지는 3x3 행렬을 만드세요
np.random.seed(seed = 1000)
random = np.random.uniform(1,10,9).reshape(3,3)
print(random)

[[6.88230627 2.03506249 9.55254578]
 [5.33972261 8.85227082 2.91099413]
 [1.36638662 4.57475015 3.09818978]]


In [23]:
#9 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요

random1 = np.array(random).flatten()
print(random1[np.argmax(random1)], random1[np.argmin(random1)])
print(np.max(random), np.min(random))

9.552545779141221 1.366386622921802
9.552545779141221 1.366386622921802


In [18]:
#10 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요
print(np.mean(random,axis = 1))
print(np.mean(random,axis = 0))

[6.15663818 5.70099585 3.01310885]
[4.52947183 5.15402782 5.18724323]
